name: Create Release

on: [workflow_dispatch]

jobs:
  lint-test:
    name: Run lint-test
    uses: ./.github/workflows/pr_checks.yml

  create-release-branch:
    runs-on: ubuntu-latest
    needs: [lint-test]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get current run number
        id: run-number
        run: echo "run_number=${{ github.run_number }}" >> $GITHUB_ENV
      - name: Configure Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
      - name: Create and push release branch
        run: |
          git checkout -b releases/${{ github.run_number }}
          git push origin releases/${{ github.run_number }}
