name: Release Fix

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version'
        required: true
        default: 'v1.0.0'
      issue-number:
        description: 'Issue number ID'
        required: true

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ steps.set-branch-name.outputs.branch_name }}

    steps:
      - name: Set up branch name
        id: set-branch-name
        run: |
          echo "::set-output name=branch_name::releases/${{ github.event.inputs.release_version }}"

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.set-branch-name.outputs.branch_name }}

  lint-test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.setup.outputs.branch_name }}

      - name: Run lint and test
        run: |
          npm run lint
          npm run test
