name: Release Fix

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version'
        required: true
      issue_number:
        description: 'Issue number ID'
        required: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.release_version }}
      - run: npm ci
      - run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.release_version }}
      - run: npm ci
      - run: npm run test

  create-docker-images-fix:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.release_version }}

      - name: Extract release number
        id: extract_number
        uses: actions/github-script@v6
        with:
          script: |
            const releaseVersion = '${{ inputs.release_version }}';
            const num = releaseVersion.split('/')[1];
            core.exportVariable('VER', num);

      - name: Login YC with Yandex ID token
        run: docker login --username oauth --password ${{ secrets.YC_TOKEN }} cr.yandex

      - name: Create and push Docker images
        run: |
          docker build -t cr.yandex/${{ secrets.ID_CONTAINER_REGISTRY }}/app:${{ env.VER }}_fix${{ github.run_number }} .
          docker build -t cr.yandex/${{ secrets.ID_CONTAINER_REGISTRY }}/app:${{ env.VER }}_latest .
          docker push cr.yandex/${{secrets.ID_CONTAINER_REGISTRY}}/app:${{ env.VER }}_fix${{ github.run_number }}
          docker push cr.yandex/${{secrets.ID_CONTAINER_REGISTRY}}/app:${{ env.VER }}_latest

  create-tag:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.release_version }}

      - name: Extract release number
        id: extract_number
        uses: actions/github-script@v6
        with:
          script: |
            const releaseVersion = '${{ inputs.release_version }}';
            const num = releaseVersion.split('/')[1];
            core.exportVariable('VER', num);

      - name: Create and push tag
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git fetch --tags
          TAG=${{ env.VER }}_fix${{ github.run_number }}
          git tag -a $TAG -m "Tagging version $TAG"
          git push origin $TAG

  add_comment_to_issue:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.release_version }}

      - name: Get previous tag
        id: get_previous_tag
        run: |
          # Get the previous tag
          PREV_TAG=$(git tag --sort=-creatordate | grep -E '^v[0-9]+.[0-9]+.[0-9]+$' | head -n 1)
          echo "PREV_TAG=$PREV_TAG" >> $GITHUB_ENV

      - name: Get commit messages from previous tag
        id: get_commits
        run: |
          # Get commits since the previous tag
          COMMITS=$(git log ${{ env.PREV_TAG }}..HEAD --pretty=format:"%h - %s (%an, %ar)")
          echo "COMMITS=$COMMITS" >> $GITHUB_ENV

      - name: Add comment to issue
        uses: actions/github-script@v6
        with:
          script: |
            const issue_number = ${{ inputs.issue_number }};
            const ver = '${{ env.VER }}';
            const run_number = '${{ github.run_number }}';
            const docker_image = `cr.yandex/${{ secrets.ID_CONTAINER_REGISTRY }}/app:${ver}_fix${run_number}`;
            const date = new Date().toLocaleDateString();
            const author = '${{ github.actor }}';
            const commits = process.env.COMMITS;

            const comment = `
            **Fix Date:** ${date}
            **Author:** ${author}
            **Commits since last release:**
            ${commits}
            **Docker Image:**
            [${docker_image}](${docker_image})
            `;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: comment
            });
